### ISSUE TITLE
any plan for the release

### ISSUE THREAD

**Issue by BaohaoLiao** [Qualcomm-AI-research/pruning-vs-quantization#1]
Hi,

I just finished reading this paper and want to reproduce some results of the paper. May I ask whether you have some specific plan for the release of this code?

**Comment by oderooij-qc** [comment]
Hi Baohao Liao,

Thank you for reading the paper, and for wanting to reproduce it! The code was initially released on December 15th, and we've just pushed an update with missing files.

Thank you,

Ork de Rooij
